<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Description>Provides a cached HTTP client configured for a Zendesk account and authentication credential.</Description>
        <Version Condition="'$(BUILD_VERSION)' == ''">4.0.0</Version>
        <Version Condition="'$(BUILD_VERSION)' != ''">$(BUILD_VERSION)</Version>
        <AssemblyName>Soenneker.Zendesk.HttpClients</AssemblyName>
        <PackageId>Soenneker.Zendesk.HttpClients</PackageId>
        <PackageTags>zendesk httpclients api openapi client httpclient singleton zendeskopenapihttpclient csharp dotnet c# .net</PackageTags>
        <Copyright>Copyright © 2026 Jake Soenneker</Copyright>
        <Authors>Jake Soenneker</Authors>
        <Company>https://soenneker.com</Company>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/soenneker/soenneker.zendesk.httpclients</PackageProjectUrl>
        <RepositoryUrl>https://github.com/soenneker/soenneker.zendesk.httpclients</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <LangVersion>latest</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>

        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Soenneker.Extensions.Configuration" Version="4.0.872" />
        <PackageReference Include="Soenneker.Utils.HttpClientCache" Version="4.0.2055" />
    </ItemGroup>
</Project>
